
services:
  database:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: database
    volumes:
      - ./mariadb-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database